# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Pay-As-You-Go (3f630b95-adea-4f0f-b00b-951bfd6478ed)'
    subscriptionId: '3f630b95-adea-4f0f-b00b-951bfd6478ed'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'mynewrg'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'https://raw.githubusercontent.com/ahmet-can-babaoglu/azure-quickstart-templates/master/quickstarts/microsoft.storage/storage-account-create/azuredeploy2.json'
    deploymentMode: 'Incremental'